version: "3"
services:
  main_site_db:
    image: "postgres"
    build:
      context: .
      dockerfile: Dockerfile.postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main_site
    ports:
      - 8085:5432

    volumes:
      - ./main_site/postgres-data:/var/lib/postgresql/data/
  site_2:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 8083:1433
    volumes:
      - ./site-2/mssql-data:/var/lib/mssqlql
    env_file:
      - site-2/mssql.env

  site_3:
    image: mysql
    restart: always
    env_file:
      - site-3/mysql.env
    ports:
      - 3306:3306
    volumes:
      - ./site-3/mysql-data:/var/lib/mysql
